---
title: "8. Covariates"
output:
  bookdown::html_document2:
    base_format: rmarkdown::html_vignette
    fig_caption: yes
    toc: true
    toc_depth: 2
    number_sections: true
pkgdown:
  as_is: true
vignette: >
  %\VignetteIndexEntry{8. Covariates}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: references.bib
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction

```{r}
suppressPackageStartupMessages({
  library(bage)
  library(poputils)
  library(dplyr)
  library(ggplot2)
})
set.seed(0)
```


```{r}
sample_times <- seq(2011, 2023, 4)
sample_regions <- kor_births |>
  pull(region) |>
  levels() |>
  sample(size = 5)
```


```{r}
mod_base <- mod_pois(births ~ age * region + age * time + region * time,
                     data = kor_births,
                     exposure = popn) |>
  set_prior(time ~ RW2()) |>
  fit()
mod_base
```

```{r}
aug_base <- mod_base |>
  augment()
aug_base
```

```{r}
plotdata_base <- aug_base |>
  filter(time %in% sample_times,
         region %in% sample_regions) |>
  mutate(draws_ci(.fitted))
  
ggplot(plotdata_base, aes(x = age_mid(age))) +
  facet_grid(vars(region), vars(time)) +
  geom_ribbon(aes(ymin = .fitted.lower,
                  ymax = .fitted.upper),
              color = "lightblue") +
  geom_line(aes(y = .fitted.mid),
            color = "darkblue")
```


```{r}
mod_covar <- mod_pois(births ~ age + time,
                      data = kor_births,
                      exposure = popn) |>
  set_covariates(~ log_gdp_pc)
mod_covar
```

```{r}
mod_covar <- mod_covar |>
  fit()

aug_covar <- mod_covar |> 
  augment()

plotdata_covar <- aug_covar |>
  filter(time %in% sample_times,
         region %in% sample_regions) |>
  mutate(draws_ci(.fitted))
  
ggplot(plotdata_covar, aes(x = age_mid(age))) +
  facet_grid(vars(region), vars(time)) +
  geom_ribbon(aes(ymin = .fitted.lower,
                  ymax = .fitted.upper),
              color = "lightblue") +
  geom_line(aes(y = .fitted.mid),
            color = "darkblue")
```


```{r}
covariates <- mod_covar |>
  components() |>
  filter(term == "covariates")
covariates
```

```{r}
tfr <- aug_covar |>
  count(region, time, wt = 5 * .fitted, name = "tfr") |>
  mutate(tfr_mid = draws_median(tfr))
```

```{r}
ggplot(tfr, aes(x = time, y = tfr_mid)) +
  facet_wrap(vars(region)) +
  geom_line()
```

```{r}
kor_births <- kor_births |>
  mutate(is_2020 = time == 2020)
mod_2020 <- mod_pois(births ~ (age + region + time)^2, 
                     data = kor_births,
                     exposure = popn) |>
  set_covariates(~ is_2020) |>
  fit()
mod_2020 |>
  components() |>
  filter(term == "covariates") |>
  print(n = Inf)
```

```{r}
kor_births <- kor_births |>
  mutate(is_2020 = time == 2020)
mod_2020 <- mod_pois(births ~ (age + region + time)^2, 
                     data = kor_births,
                     exposure = popn) |>
  set_covariates(~ is_2020) |>
  fit()
mod_2020 |>
  components() |>
  filter(term == "covariates") |>
  print(n = Inf)
```

```{r}
kor_births <- kor_births |>
  mutate(reg_2020 = if_else(time == 2020, region, "baseline"))
```


```{r}
mod_reg2020 <- mod_pois(births ~ age * region + age * time + region * time, 
                        data = kor_births,
                        exposure = popn) |>
  set_covariates(~ reg_2020, n_nonzero = 5) |>
  fit()
mod_reg2020 |>
  components() |>
  filter(term == "covariates") |>
  print(n = Inf)
```



```{r}
mod_reg2020 |>
  components() |>
  filter(term == "covariates" & component == "coef") |>
  mutate(val = draws_median(.fitted)) |>
  ggplot(aes(x = val, y = level)) +
  geom_point()
```

