---
title: "vig_1_intro"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vig_1_intro}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(bage)
library(dplyr)
library(ggplot2)
```

```{r}
mod <- mod_pois(injuries ~ age : sex + age : ethnicity + year,
                data = injuries,
                exposure = popn) %>%
  set_prior(year ~ AR1())
mod
```

```{r}
mod <- mod %>%
  fit()
mod
```

```{r}
tidy(mod)
```

```{r}
augment(mod)
```


Plot fitted values with 95% credible intervals (<span style="color: darkblue;">blue</span>) and direct estimates (<span style="color: darkorange;">orange</span>).

```{r fig, fig.width = 7, fig.height = 5}
mod %>%
  augment() %>%
  filter(year >= 2017) %>%
  ggplot(aes(x = age, y = .fitted)) +
  facet_grid(vars(sex), vars(year)) +
  geom_point(aes(y = .observed), 
             col = "darkorange") +
  geom_pointrange(aes(ymin = .lower, ymax = .upper),
                  fatten = 0.5,
                  color = "darkblue")
```

```{r}
components(mod, type = "par")
```


```{r}
components(mod, type = "hyper")
```


# Model

\begin{align}
y & \sim \text{Poisson}(\mu w) \\
\log \mu & = X \beta \\
\beta & \sim N(\pmb{0}, \pmb{\Sigma})
\end{align}

(Currently every $\beta$ has a normal prior)

<!-- I suggest we add an error term, using the set-up from [Dan Simpson blog entry](https://dansblog.netlify.app/posts/2022-08-29-priors4/priors4.html) -->
<!-- \begin{align} -->
<!-- y & \sim \text{Poisson}(\mu u w) \\ -->
<!-- \log \mu & = X \beta \\ -->
<!-- \beta & \sim N(\pmb{0}, \pmb{\Sigma}) \\ -->
<!-- u & \sim \text{Gamma}(\alpha^{-1}, \alpha^{-1}) -->
<!-- \end{align} -->
<!-- (which can be converted to a negative binomial model). -->



