# Generated by cpp11: do not edit by hand

make_age_effect <- function(terms, dim, mappings, b, X) {
  .Call(`_bage_make_age_effect`, terms, dim, mappings, b, X)
}

make_linear_pred <- function(terms, dim, mappings) {
  .Call(`_bage_make_linear_pred`, terms, dim, mappings)
}
