# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Assemble effects involving age for a single
#' draw from the posterior distribution
#'
#' Assemble terms that represent an age or age-sex
#' effect within a subspace, then transform back
#' to the original space. The calculations are
#' carried out on a single draw from the posterior
#' distribution.
#'
#' Each element of \code{terms} is composed
#' of one or more vectors describing a point
#' within the subspace. For instance an age-time
#' interaction would be a matrix, each column
#' of which represented a single time point,
#' and each row of which represented distance
#' along the c'th dimension of the subspace.
#' The matrix (or array) is implicit, in that
#' the terms themselves do not have \code{dim}
#' attributes.
#'
#' \code{dim} is the dimension of an array
#' formed by combining all the non-age (or non-age-sex)
#' dimensions in \code{terms}. For instance, if the
#' elements of \code{terms} represent an age effect,
#' an age-time interaction, and an age-region
#' interaction, then the (implicit) array
#' has two dimensions: time and region.
#'
#' Each element of \code{mappings} gives the
#' indices of the array described above
#' that the corresponding element of \code{terms}
#' maps on to. An element of length 0
#' is used to represent a pure age (or age-sex)
#' effect.
#'
#' @param terms List of numeric vectors.
#' @param dim The dimensions of the array
#' that could be formed by all the non-age
#' dimensions.
#' @param mappings List of integer vectors,
#' the same length as \code{terms}.
#' @param b,X Numeric vector and matrix used
#' to convert back to the original space.
#'
#' @return An array, the first dimension
#' of which is age or age-sex.
#'
#' @export
make_age_effect <- function(terms, dim, mappings, b, X) {
    .Call(`_bage_make_age_effect`, terms, dim, mappings, b, X)
}

#' Assemble linear predictor by assembling contributions
#' of main effect and interactions
#'
#' Assemble terms that representing main effects
#' or interactions (eg age:time interactions),
#' to create linear predictor with the same
#' dimensions as the array of outcomes being modelled.
#'
#' Each element of \code{terms} is a single draw from the
#' posterior distribution for tha that term.
#'
#' \code{dim} is the dimension of the array
#' of outcomes, and hence of the linear predictor.
#'
#' Each element of \code{mappings} gives the
#' indices of the array that the corresponding
#' element of \code{terms} maps on to.
#'
#' @param terms List of numeric vectors.
#' @param dim The dimensions of the array
#' to be constructed.
#' @param mappings List of integer vectors,
#' the same length as \code{terms}.
#'
#' @return An array, with the dimension
#' specified by \code{dim}.
#'
#' @export
make_linear_pred <- function(terms, dim, mappings) {
    .Call(`_bage_make_linear_pred`, terms, dim, mappings)
}

